### ISSUE TITLE
Undefined method `call' for Bridge:Class

### ISSUE THREAD

**Issue by Aerilius** [Aerilius/sketchup-bridge#43]
> Hi. Sorry for my english. I just espeak portuguese. So, lets go. I trying to use Bridge.call on Sketchup 2022 and I have this issue: 
> 
> "undefined method `call' for PRBO::Devix::Bridge:Class (Line 1)"
> Error: #<TypeError: no implicit conversion of NoMethodError into String>
> C:/Users/paulo/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/as_rubyeditor/as_rubyeditor.rb:346:in `+'
> C:/Users/paulo/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/as_rubyeditor/as_rubyeditor.rb:346:in `rescue in block in initialize'
> C:/Users/paulo/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/as_rubyeditor/as_rubyeditor.rb:344:in `block in initialize'
> 
> my code: 
> ```ruby
> module PRBO
>     module Devix    
>     
>     class DialogBox
>     attr_accessor :dlg
>     def initialize
>         dialog = UI::HtmlDialog.new({
>           :dialog_title => "Plugin Devix",
>           :preferences_key => "com.sample.plugin",
>           :scrollable => true,
>           :resizable => true,
>           :width => 1000,
>           :height => 1000,
>           :left => 100,
>           :top => 100,
>           :min_width => 800,
>           :min_height => 50,
>           :style => UI::HtmlDialog::STYLE_DIALOG
>         })
>         dialog.set_file('c:/DevixPlugin/html/index.html')
>         @dlg = dialog
>     end
>   end   
> 
> 
> 
> 
>     load "c:/DevixPlugin/lib/bridge/bridge.rb"
>   
>     def self.showMenu 
>         dlg_menu = DialogBox.new
>         dlg = dlg_menu.dlg
>         Bridge.decorate(dlg)
>         #Bridge.new(dlg)
> 
>         dlg.on('ponte') {|deferred, mensagemponte|
>             p mensagemponte
>             deferred.resolve(1000)
>         }
> 
>         dlg.show
>         Bridge.call('borogodo','testando')
>     end
>     showMenu
> 
>     end
> end
> ```
> 
> ############ my index.html
> ```html
> <!DOCTYPE html>
> <html lang="pt-br">
> <head>
>     <meta charset="UTF-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>Devix - Tools</title>
>     <style>
>         * {
>             margin: 0;
>             padding: 0;
>         }
>     </style>
>     <script type="text/javascript" src="./js/bridge.js"></script>
> </head>
> <body>
>     <div class="container">
>         <div class="Button">
>             <button type="button" id="teste">Teste click</button>
>         </div>
>     </div>
>     <script type="text/javascript">
>         var botao = document.getElementById('teste');
>         botao.addEventListener('click', function(event) {
>             Bridge.get('ponte', 'mariola').then(function (testando) {
>                 window.alert(testando); 
>             });
>         });
>         function borogodo() {
>             window.alert("Mensagem vinda do Sketchup"); 
>         };
>     </script>
>     
> </body>
> </html>
> ```
> 
> ################
> when a click on button on the html file, the Bridge works. I wanna make work from sketchup. On event, call a function on index.html and return some data.

_Originally posted by @PRBO84 in https://github.com/Aerilius/sketchup-bridge/issues/13#issuecomment-1246224697_

**Comment by Aerilius** [comment]
Hi @PRBO84,

I took the liberty to move your question into a new thread because it is not related to the topic [Fix JSON lib version check](https://github.com/Aerilius/sketchup-bridge/pull/13).

I believe the cause for the error that you see is that you called an instance method on a class, not its instance. `Bridge` is a class which has only limited functionality, namely creating new bridge objects. For example, it has no class method `call`. That is why Ruby documentation has the convention to prefix class methods with a `.` and instance methods with a `#` (like `Bridge#call`).

But if you used
```ruby
bridge = Bridge.new(dlg)
```
then the instance `bridge` has a method `call`. This makes sure that the method only operates on this instance of the class Bridge and not on other instances.

`Bridge.decorate` is meant to be a shortcut for adding this functionality to an existing object (like the dialog), so that you don't have to interact with two different objects. That means the `call` method is now also available on the dialog. So you should be able to do:
```ruby
dlg.call('borogodo','testando')
```

**Comment by PRBO84** [comment]
Hi Aerilius. 

Thank you so much! It's works.
